spring.application.name=backend

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/lavanderia_db
spring.datasource.username=postgres
spring.datasource.password=s1s2s3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true